In [107]:
import numpy as np

In [108]:
array1 = np.random.randint(1,30,size=20)
array1

array([ 4, 15,  6,  8,  6, 25, 26, 18, 13, 15, 25, 14,  6, 12,  8,  4, 25,
       10,  9, 22])

In [109]:
array2 = np.random.randint(6,50,size=15)
array2

array([12,  9, 25, 15, 44,  7, 37, 11,  6, 49, 23, 41, 35, 26, 46])

In [110]:
#Question 11

In [111]:
max_value = np.max(array1)
max_value

26

In [112]:
min_value = np.min(array1)
min_value

4

In [113]:
#Question 12

In [114]:
mean = np.mean(array1)
mean

13.55

In [115]:
median = np.median(array1)
median

12.5

In [116]:
st_dev = np.std(array1)
st_dev

7.399155357201253

In [117]:
#Question 13

In [118]:
arraysum = np.sum(array1)
arraysum

271

In [119]:
#Question 14 cumulative sum 
print(np.cumsum(array1))

[  4  19  25  33  39  64  90 108 121 136 161 175 181 193 201 205 230 240
 249 271]


In [120]:
#Question 15
sub1 = array1[2:12]
sub2 = array1[-14:-3]
print(sub1)
print(sub2)

[ 6  8  6 25 26 18 13 15 25 14]
[26 18 13 15 25 14  6 12  8  4 25]


In [121]:
print(np.split(array1, 4))

[array([ 4, 15,  6,  8,  6]), array([25, 26, 18, 13, 15]), array([25, 14,  6, 12,  8]), array([ 4, 25, 10,  9, 22])]


In [122]:
#Question 16
arr1_arr2 = np.concatenate((array1, array2), axis=0)
arr1_arr2

array([ 4, 15,  6,  8,  6, 25, 26, 18, 13, 15, 25, 14,  6, 12,  8,  4, 25,
       10,  9, 22, 12,  9, 25, 15, 44,  7, 37, 11,  6, 49, 23, 41, 35, 26,
       46])

In [123]:
#Question3
arr3 = array2.reshape((3,5))

arr1_arr2_2 = np.concatenate((arr3, arr3), axis=1)
arr1_arr2_2

array([[12,  9, 25, 15, 44, 12,  9, 25, 15, 44],
       [ 7, 37, 11,  6, 49,  7, 37, 11,  6, 49],
       [23, 41, 35, 26, 46, 23, 41, 35, 26, 46]])

In [124]:
#Question17

In [125]:
array4 = np.random.randint(14,60,size=20)

In [126]:
print(np.hstack((array1,array2)))

[ 4 15  6  8  6 25 26 18 13 15 25 14  6 12  8  4 25 10  9 22 12  9 25 15
 44  7 37 11  6 49 23 41 35 26 46]


In [127]:
print(np.vstack((array1,array4)))

[[ 4 15  6  8  6 25 26 18 13 15 25 14  6 12  8  4 25 10  9 22]
 [16 58 56 50 22 57 36 58 45 56 31 28 34 54 19 54 21 48 52 56]]


In [128]:
#Question18

In [129]:
arr3

array([[12,  9, 25, 15, 44],
       [ 7, 37, 11,  6, 49],
       [23, 41, 35, 26, 46]])

In [137]:
print(arr3[1:3,2:4])

[[11  6]
 [35 26]]


In [138]:
#Question19

In [139]:
array5 = np.copy(arr3)
array5

array([[12,  9, 25, 15, 44],
       [ 7, 37, 11,  6, 49],
       [23, 41, 35, 26, 46]])

In [140]:
#Question20

In [141]:
print(np.unique(arr1_arr2_2))

[ 6  7  9 11 12 15 23 25 26 35 37 41 44 46 49]


In [142]:
#Question21

In [145]:
np.intersect1d(ar1= arr1_arr2, ar2=arr1_arr2_2)

array([ 6,  7,  9, 11, 12, 15, 23, 25, 26, 35, 37, 41, 44, 46, 49])

In [149]:
np.setdiff1d(ar1= arr1_arr2, ar2=arr1_arr2_2)

array([ 4,  8, 10, 13, 14, 18, 22])

In [150]:
#Question22

In [151]:
print(array5>20)

[[False False  True False  True]
 [False  True False False  True]
 [ True  True  True  True  True]]


In [152]:
print(arr3==array5)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [153]:
#Question23

In [154]:
print(array5 + 12)

[[24 21 37 27 56]
 [19 49 23 18 61]
 [35 53 47 38 58]]


In [156]:
print(array5 / 4)

[[ 3.    2.25  6.25  3.75 11.  ]
 [ 1.75  9.25  2.75  1.5  12.25]
 [ 5.75 10.25  8.75  6.5  11.5 ]]


In [157]:
#Question1 & Question2

In [158]:
array6 = np.arange(2,45,3)
array6

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [159]:
#Question4-7

In [166]:
print(array5.shape)
print(array5.ndim)
print(array5.size)
print(array5.dtype)

(3, 5)
2
15
int64


In [163]:
#Question8

In [167]:
array6_float = array5.astype('float')
array6_float

array([[12.,  9., 25., 15., 44.],
       [ 7., 37., 11.,  6., 49.],
       [23., 41., 35., 26., 46.]])

In [168]:
array6_string = array5.astype('str')
array6_string

array([['12', '9', '25', '15', '44'],
       ['7', '37', '11', '6', '49'],
       ['23', '41', '35', '26', '46']], dtype='<U21')

In [170]:
#question9 & 10

In [172]:
ones_array = np.ones((3,6),dtype="int")
zeros_array = np.zeros((4,3),dtype="int")
print(ones_array)
print(zeros_array)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
