# Assignment 1 NumPy



In [193]:
#Import the libraries 
import numpy as np

# Problem 1 
Matrix Manipulations

Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [194]:
A = np.array([[3,5,9],[3,3,4],[5,9,17]])
B = np.array((2,1,4)).reshape(3,1)

x = np.linalg.solve(A, B)
print(x)

[[ 1.]
 [-2.]
 [ 1.]]


In [195]:
Ax = np.matmul(A,x)
print(Ax)

[[2.]
 [1.]
 [4.]]


In [196]:
if np.allclose(Ax, B.astype('float')):
    print("Ax = B verified")

Ax = B verified


# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



In [197]:
arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])
resultarray = arrayOne + arrayTwo
print(resultarray)

[[20 39 33]
 [25 25 28]]


In [198]:
resultarray = np.square(resultarray)
print(resultarray)

[[ 400 1521 1089]
 [ 625  625  784]]


# Problem 3
Print max from axis 0 and min from axis 1 from the following 2-D array.\
$$sampleArray = \left[\begin{array}{ccc} 34&43&73 \\ 82&22&12 \\ 53&94&66 \end{array}\right]$$




In [199]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [200]:
print(np.max(sampleArray, axis=0))

[82 94 73]


In [201]:
print(np.min(sampleArray, axis=1))

[34 12 53]


# Problem 4
Get the positions where elements of a and b match\
Input:  `a = np.array([1,2,3,2,3,4,3,4,5,6])\
b = np.array([7,2,10,2,7,4,9,4,9,8])`\
Desired Output: array([1, 3, 5, 7])

In [202]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [203]:
output = np.where(a==b)
output = output[0].flatten()
print(output)

[1 3 5 7]


# Problem 5
Given 
$$a= \left[\begin{array}{cc} 1&2\\ 3&4 \end{array}\right]$$
$$b = \left[\begin{array}{cc} 5&6 \\ 7&8 \end{array}\right]$$
Obtain c and d
$$c = \left[\begin{array}{cc} 1&2\\ 3&4 \\ 5&6 \\ 7&8 \end{array}\right]$$
$$d = \left[\begin{array}{cccc} 1&2&5&6\\ 3&4&7&8 \end{array}\right]$$

In [204]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)

In [205]:

c = np.concatenate((a, b), axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [206]:
d = np.concatenate((a, b), axis=1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])